//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.06 at 12:52:39 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/")
package com.ceiba.infraestructura.soap;
