//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.06 at 12:52:39 AM COT 
//


package com.ceiba.infraestructura.soap;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for queryTCRM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queryTCRM"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tcrmQueryAssociatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queryTCRM", propOrder = {
    "tcrmQueryAssociatedDate"
})
@XmlRootElement
public class QueryTCRM {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar tcrmQueryAssociatedDate;

    /**
     * Gets the value of the tcrmQueryAssociatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTcrmQueryAssociatedDate() {
        return tcrmQueryAssociatedDate;
    }

    /**
     * Sets the value of the tcrmQueryAssociatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTcrmQueryAssociatedDate(XMLGregorianCalendar value) {
        this.tcrmQueryAssociatedDate = value;
    }

}
